<?php
session_start();
include 'connection/conn.php';

if(!isset($_SESSION['customer_id'])){
  header("location:login.php");
}

$apiKey = "rzp_test_pLl681e9OrLq4X";

$u_id = $_SESSION['customer_id'];
$profile_data = $con->query("select * from customer where customer_id='$u_id'");
$profile = $profile_data->fetch_object();

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RMS | Payment</title>
  <?php include 'link.php' ?>
</head>
<style type="text/css">
  
</style>
<body class="body-wrapper">
<?php include 'header.php' ?>
<section class="page-title">
  <!-- Container Start -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <!-- Title text -->
        <h3>Make Payment</h3>
      </div>
    </div>
  </div>
  <!-- Container End -->
</section>
<section  class="login py-5 border-top-1">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12 col-md-8 align-item-center">
       <div class="card ">
        <div class="card-header bg-danger text-white">Make Payment using RazorPay</div>
        <div class="card-body">
          <form action="http://localhost/RMS/user/success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo intval($_SESSION['amount']) * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $_SESSION['order_id'];?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Restaurant Management System"
    data-description="Have Food Like Home"
    data-image="https://ajrms.000webhostapp.com/logo1.PNG"
    data-prefill.name="<?php echo $profile->name; ?>"
    data-prefill.email="<?php echo $profile->email;?>"
    data-prefill.contact="<?php echo $profile->contact;?>"
    data-theme.color="#ff9902"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
        </div>
      </div>


              
       
      </div>
    </div>
  </div>
</section>
<?php include 'footer.php' ?>
<!-- 
Essential Scripts
=====================================-->
<script src="plugins/jquery/jquery.min.html"></script>
<script src="plugins/bootstrap/popper.min.js"></script>
<script src="plugins/bootstrap/bootstrap.min.js"></script>
<script src="plugins/bootstrap/bootstrap-slider.js"></script>
<script src="plugins/tether/js/tether.min.js"></script>
<script src="plugins/raty/jquery.raty-fa.js"></script>
<script src="plugins/slick/slick.min.js"></script>
<script src="plugins/jquery-nice-select/js/jquery.nice-select.min.js"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" defer></script>
<script src="plugins/google-map/map.js" defer></script>
<script src="js/script.js"></script>
</body>
</html>